[tool.poetry]
name = "toxicbackend"
version = "0.1.0"
description = ""
authors = ["Tibor Cus <tibor.cus@itsv.at>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
django = "^5.1.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
